version: '3'

services:
  pxe:
    image: ferrarimarco/pxe:1
    restart: always
    volumes:
    - /home/Peedy/Projects/tftp-ubuntu-installation/pxe/pxe.conf:/etc/dnsmasq.conf
    - /home/Peedy/Projects/tftp-ubuntu-installation/pxe/tftpboot:/var/lib/tftpboot
    network_mode: "host"
    cap_add:
      - NET_ADMIN