#!/bin/bash

netmask="24"
gateway="192.168.123.1"
dns_nm="9.9.9.9;1.1.1.1"  #NetworkManager entries are separated by semicolon!
domain="example.org"
ubuntu_proxy="192.168.123.180"

declare -A hosts=(
    [n0a]=00:bf
    [n0b]=00:bf
    [n0c]=00:bf
    [ubuntu-test]=52:54:00:bd:a2:f3
)

declare -A IPs=(
    [n0a]=192.168.0.2
    [n0b]=192.168.0.3
    [n0c]=192.168.0.4
    [ubuntu-test]=192.168.123.222
)