#!/bin/bash

netmask="24"
gateway="192.168.123.1"
dns_nm="9.9.9.9;1.1.1.1"  #NetworkManager entries are separated by semicolon!
dns="9.9.9.9,1.1.1.1"
domain="example.org"
ubuntu_proxy="192.168.123.180"

declare -A hosts=(
    [n0a]=00:bf
    [cc01]=c8:d9:d2:0f:d6:6f
    [ubuntu-test]=52:54:00:bd:a2:f3
    [ubuntu-x2]=52:54:00:35:e4:5a
)

declare -A IPs=(
    [n0a]=192.168.0.2
    [cc01]=192.168.123.11
    [ubuntu-test]=192.168.123.222
    [ubuntu-x2]=192.168.123.223
)